# CREATE database dns_timestamp;

CREATE TABLE dnsrr
(
	NAME VARCHAR(270) NOT NULL,
    TYPE VARCHAR(50),
    CLASS VARCHAR(50),
    TTL INT,
    RDATA VARCHAR(480) NOT NULL,
    TIMESTAMP INT,
    PRIMARY KEY (NAME,RDATA)
    )DEFAULT CHARSET=utf8mb4;
    